[package]
name = "raca-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rc_object_derive = { path = "../rc_object_derive" }
downcast-rs = { version = "1.2.0", default-features = false }
bitflags = "2.6.0"
spin = "0.9.8"
