[package]
name = "module_std"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = {git="https://github.com/rust-osdev/x86_64"}
spin = "0.9.8"

[dependencies.log]
version = "0.4.22"
default-features = false
