[unstable]
bindeps = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins" , "alloc"]

[build]
target = "target.json"

[target.'cfg(target_os = "none")']
rustflags = ["-C","code-model=large"]



